import './globals.css'
import type { Metadata } from 'next'
import { Inter, Montserrat } from 'next/font/google'
import { getSession, SessionProvider } from "next-auth/react"
import { auth } from '../../auth'
import { Toaster } from '@/components/ui/toaster'
import PreviewProvider from '../../context/triggerPreview'
const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth();


  return (
    <html lang="en">
      <body className={montserrat.className}>
        <SessionProvider session={session}>
          <PreviewProvider>
            {children}
          </PreviewProvider>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  )
}
